Repository mvondracek/PA193_mnemonic_Slytherin, pull requests merged in 2019-10, with the labels that each got.

#27 typo: docs: mnemoniccli.Config.Format used only forentropy and seed, …
  PA193_mnemonic_Slytherin/mnemoniccli.py
Labels: documentation

#31 Test coverage using coveralls with intergration for Travis and GitHub.
  .travis.yml
  PA193_mnemonic_Slytherin/test_mnemonic.py
  PA193_mnemonic_Slytherin/test_mnemoniccli.py
  README.md
  setup.py
Labels: analysis, enhancement

#32 Static analysis using Code Climate
  .codeclimate.yml
  CONTRIBUTING.md
  PA193_mnemonic_Slytherin/mnemoniccli.py
  PA193_mnemonic_Slytherin/test_mnemoniccli.py
  README.md
  setup.cfg
Labels: analysis, enhancement

#49 Fix generate seed invalid password too long
  PA193_mnemonic_Slytherin/mnemonic.py
  PA193_mnemonic_Slytherin/mnemoniccli.py
  PA193_mnemonic_Slytherin/test_mnemonic.py
Labels: bug

#54 tests: _DictionaryAccess: test invalid_dictionary_lines
  PA193_mnemonic_Slytherin/test_mnemonic.py
Labels: bug

#57 Task 39 fuzzer
  .codeclimate.yml
  README.md
  fuzz/clean.sh
  fuzz/install.sh
  fuzz/run.sh
  fuzz/test_entropy_bin
  fuzz/test_entropy_hex
  fuzz/test_mnemonic_str
  fuzz/test_seed_bin
  fuzz/test_seed_hex
Labels: enhancement

#64 Encoding issues fix refactor
  pa193mnemonicslytherin/mnemoniccli.py
  pa193mnemonicslytherin/test_mnemonic.py
  pa193mnemonicslytherin/test_mnemoniccli.py
Labels: analysis, bug

#65 Mnemoniccli/exceptions
  pa193mnemonicslytherin/mnemoniccli.py
Labels: analysis, enhancement

#60 Resolving encoding issues
  fuzz/run.sh
  pa193mnemonicslytherin/mnemonic.py
  pa193mnemonicslytherin/mnemoniccli.py
  pa193mnemonicslytherin/test_mnemonic.py
  pa193mnemonicslytherin/test_mnemoniccli.py
Labels: bug

#66 change in fuzzing to enable running in travis
  fuzz/run.sh
Labels: enhancement
